language: node_js
node_js:
  - "0.12"
  - "4"
  - "stable"

cache:
  directories:
    - node_modules

script:
  - npm test
  - npm run dist

after_success:
  - chmod +x "$TRAVIS_BUILD_DIR/ci/deploy.sh"
  - ${TRAVIS_BUILD_DIR}/ci/deploy.sh

after_script:
  - npm run coveralls

# See https://github.com/travis-ci/travis-ci/issues/5538
#deploy:
#  skip_cleanup: true
#  provider: script
#  script: ci/deploy.sh
#  on:
#    tags: true
#    node: "stable"
