branches:
  only:
    - master

environment:
  nodejs_version: "5.5.0"

install:
  - ps: Install-Product node $env:nodejs_version x86
  - ps: choco install --x86 -yf InnoSetup

build_script:
  - ps: ci\windows\build.ps1
